# THIS FILE PROVIDES BUILD CONFIG FOR LABELER API

version: "3.9"

services:
  labeler_db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "54320:5432"
    networks:
      - labeler_network
  labeler_api:
    build: labeler_api/
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - PG_USER=postgres
      - PG_PASS=postgres
      - PG_HOST=labeler_db
      - PG_PORT=5432
      - DEBUG=False
    ports:
      - "80:80"
    depends_on:
      - labeler_db
    networks:
      - labeler_network


networks:
    labeler_network:
      driver_opts:
        encrypted: ""
